### ISSUE TITLE
Question about transformer with DQN

### ISSUE THREAD

**Issue by 8JasonStatham8** [kevslinger/DTQN#4]
Hi, Kev
It's glad to know your work about DTQN.
I am very curious about why the work of combine Transformer and DQN is very small ,and this two technology is emit very early.
Because I thought there would be a lot of work in that point, but it is not.
As I know , It's maybe just one paper  'TRANSFORMER BASED REINFORCEMENT LEARNING FOR GAMES' before your work, and in that paper  DTQN is not good as DRQN.
Do you have some insight about this?

**Comment by ReinholdM** [comment]
Hi, Jason
As a combination of the transformer and Q network, I would like to point out that the memory module is critical in the implementation of the combination. The practical experience shows that a naive attention mechanism should incorporate memory, such as historical observation or reward, to work well.

**Comment by kevslinger** [comment]
Hi Jason, 

I'm sorry, I didn't see your message. Thanks for your interest in DTQN! I agree, I think transformers for reinforcement learning is an understudied field. One of the reasons for this could be that transformers are most well-suited to solve POMDPs, which is not as popular as fully-observable MDPs. Probably the 2 biggest papers for transformers in RL are [Decision Transformer](https://arxiv.org/abs/2106.01345), which is for offline RL solving MDPs, and [GTrXL](https://arxiv.org/abs/1910.06764). Neither of which use a DQN-like approach. There is also [Stabilizing Q-learning with ConvNets and ViT](https://arxiv.org/abs/2107.00644), which uses the vision transformer as an image encoder, and then DQN for action selection; this is a different use case for the transformer compared to DTQN and the 2 previous works.

In general, transformers in RL is becoming more and more popular. In particular, roboticists are leveraging the ability to use multi-modal data in transformers (thanks PerceiverIO!), such as in [PerAct](https://arxiv.org/abs/2209.05451). The Perceiver archiecture allows us to easily attend across modalities (for instance, an image of the scene and a language goal). That is a very powerful ability, which I think will become more popular. For sure, this is an exciting time to be interested in transformers.

**Comment by 8JasonStatham8** [comment]
> Hi, Jason As a combination of the transformer and Q network, I would like to point out that the memory module is critical in the implementation of the combination. The practical experience shows that a naive attention mechanism should incorporate memory, such as historical observation or reward, to work well.

Thanks for your insight. Do you ever seen some work that combination of the transformer and offline RL algorithm?

**Comment by 8JasonStatham8** [comment]
> 

Thanks for your replay. I thought Decision Transformer is more like Sequential-Modeling , GTrXL is more like  MDPs-solver. And DTQN is also like  MDPs-solver. Have you ever seen some work about offline RL algorithm with Transformer?

**Comment by kevslinger** [comment]
Decision Transformer was built to solve MDPs using offline RL. Really, it's trained in a supervised way using a dataset of transitions from the [D4RL](https://github.com/Farama-Foundation/D4RL) repo. GTrXL and DTQN both incorporate memory by using a transformer where each token is a past observation, so they can solve POMDPs. While GTrXL primarily focused on solving MDPs, it can also be applied for POMDPs. In contrast, DTQN is built for solving POMDPs.

**Comment by 8JasonStatham8** [comment]
> Decision Transformer was built to solve MDPs using offline RL. Really, it's trained in a supervised way using a dataset of transitions from the [D4RL](https://github.com/Farama-Foundation/D4RL) repo. GTrXL and DTQN both incorporate memory by using a transformer where each token is a past observation, so they can solve POMDPs. While GTrXL primarily focused on solving MDPs, it can also be applied for POMDPs. In contrast, DTQN is built for solving POMDPs.

Thanks for your insight. It's very helpful for me.
