### ISSUE TITLE
I'm trying to connect DTQN network with SUMO. I want to know inputs of DTQN.

### ISSUE THREAD

**Issue by jewookwak** [kevslinger/DTQN#7]
Hello, again.
As I mention on the title. I'm trying to connect DTQN network with SUMO as an environment. I want to know inputs of DTQN.
I think the inputs are Observations  as I read the following paper.
But I don't know the format.
I'm struggle really hard on finding the input format of DTQN.
Which python file should I check? Could you tell me the location, Please?
Furthermore, I'm trying to use  sequential numbers as states. Ex) relative distance between agent and other cars, agent's velocity and current lane number.
And I wonder DTQN architecture can handle this state as observation.
Because DQN's inputs seem like sequential images. Is DTQN's inputs are sequential images too?

**Comment by kevslinger** [comment]
In theory, DTQN can handle any observation space as input. What the network wants is that you have some sort of observation embedding layer, which independently converts each observation into a single vector (of some fixed length e.g. 128). Some embedding layers are provided for you; see the paper branch file dtqn/dtqn/networks/dtqn. To see how the agent stores and handles the observations, check out dtqn/dtqn/agents/dtqn. If you are using specialized environments and the predefined observation embedding do not work, feel free to edit your local codebase and add your own

**Comment by jewookwak** [comment]
Thank you so much for your help, I will study the codes and try it in my environment.
I will tell you if it works :)
