### ISSUE TITLE
`in-embed` instead of `inembed`?

### ISSUE THREAD

**Issue by ashok-arora** [kevslinger/DTQN#8]
In the readme, 
the flag mentioned is `--inembed` but shouldn'it it be `--in-embed`?
hence the command becomes,
```bash
python run.py --envs DiscreteCarFlag-v0 --in-embed 128 --disable-wandb --verbose
```

**Comment by kevslinger** [comment]
Hi, thank you for your interest in DTQN! I see the flag defined as `inembed` here https://github.com/kevslinger/DTQN/blob/e6ef4313ba50e2a346cb7f83bcf93118c3601c1c/run.py#L272, so I believe the README to be correct as stated

**Comment by ashok-arora** [comment]
Hi, in the `main` branch, https://github.com/kevslinger/DTQN/blob/main/run.py#L104-L109, the code is different.

**Comment by kevslinger** [comment]
Thank you, now I have updated the main branch accordingly.
