### ISSUE TITLE
Can this project run on the Windows?

### ISSUE THREAD

**Issue by Fg-droid-1014** [kevslinger/DTQN#9]
It seems that you run this project on Linux，when i tried Window and run the command "pip install -r requirements.txt"，it will prompt me  some wrong information:

----------------------------------------------------------------------------------------------------------------------------------------
Building wheels for collected packages: nle
  Building wheel for nle (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for nle (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
      fatal: not a git repository (or any of the parent directories): .g
it
      Building wheel nle-0.8.1
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\nle
      copying nle\version.py -> build\lib.win-amd64-cpython-38\nle
      copying nle\__init__.py -> build\lib.win-amd64-cpython-38\nle
      creating build\lib.win-amd64-cpython-38\nle\env
      copying nle\env\base.py -> build\lib.win-amd64-cpython-38\nle\env
      copying nle\env\tasks.py -> build\lib.win-amd64-cpython-38\nle\env

      copying nle\env\__init__.py -> build\lib.win-amd64-cpython-38\nle\
env
      creating build\lib.win-amd64-cpython-38\nle\nethack
      copying nle\nethack\actions.py -> build\lib.win-amd64-cpython-38\n
le\nethack
      copying nle\nethack\nethack.py -> build\lib.win-amd64-cpython-38\n
le\nethack
      copying nle\nethack\__init__.py -> build\lib.win-amd64-cpython-38\
nle\nethack
      creating build\lib.win-amd64-cpython-38\nle\agent
      copying nle\agent\agent.py -> build\lib.win-amd64-cpython-38\nle\a
gent
      copying nle\agent\vtrace.py -> build\lib.win-amd64-cpython-38\nle\
agent
      copying nle\agent\__init__.py -> build\lib.win-amd64-cpython-38\nl
e\agent
      creating build\lib.win-amd64-cpython-38\nle\scripts
      copying nle\scripts\check_nethack_speed.py -> build\lib.win-amd64-
cpython-38\nle\scripts
      copying nle\scripts\collect_env.py -> build\lib.win-amd64-cpython-
38\nle\scripts
      copying nle\scripts\play.py -> build\lib.win-amd64-cpython-38\nle\
scripts
      copying nle\scripts\plot.py -> build\lib.win-amd64-cpython-38\nle\
scripts
      copying nle\scripts\read_heaplog.py -> build\lib.win-amd64-cpython
-38\nle\scripts
      copying nle\scripts\read_tty.py -> build\lib.win-amd64-cpython-38\
nle\scripts
      copying nle\scripts\test_raw_nethack.py -> build\lib.win-amd64-cpy
thon-38\nle\scripts
      copying nle\scripts\ttyplay.py -> build\lib.win-amd64-cpython-38\n
le\scripts
      copying nle\scripts\ttyplay2.py -> build\lib.win-amd64-cpython-38\
nle\scripts
      copying nle\scripts\ttyrec.py -> build\lib.win-amd64-cpython-38\nl
e\scripts
      copying nle\scripts\__init__.py -> build\lib.win-amd64-cpython-38\
nle\scripts
      creating build\lib.win-amd64-cpython-38\nle\tests
      copying nle\tests\test_envs.py -> build\lib.win-amd64-cpython-38\n
le\tests
      copying nle\tests\test_nethack.py -> build\lib.win-amd64-cpython-3
8\nle\tests
      copying nle\tests\test_profile.py -> build\lib.win-amd64-cpython-3
8\nle\tests
      copying nle\tests\test_system.py -> build\lib.win-amd64-cpython-38
\nle\tests
      running build_ext
      error: [WinError 2] 系统找不到指定的文件。
      [end of output]

  note: This error originates from a subprocess, and is likely not a pro
blem with pip.
  ERROR: Failed building wheel for nle
Failed to build nle
ERROR: Could not build wheels for nle, which is required to install pypr
oject.toml-based projects

**Comment by kevslinger** [comment]
Hi, and thank you for your interest in DTQN! Unfortunately, I have never run any of my code on Windows, so I don't have any windows-specific advice to give you. It looks like the package that is causing the error is nle, which is related to NetHack, a domain I was testing with more recently, after my paper got published. To use the most stable branch of DTQN, I recommend using the `paper` branch, which does not require nle. If you would like to run the main branch and plan to test on domains other than NetHack, then feel free to remove nle from `requirements.txt` and install the dependencies. If you need to test with the NetHack domains, I don't know how to help you; but I'd be happy to review a pull request should you figure out how to install nle on windows.
